version: "3.8"

services:
	backend:
		build: ./backend
		restart: always
		ports:
			- "8080:8080"
		environment:
			- MYSQL_DSN=$(MYSQL_DSN)
			- REDIS_ADDR=$(REDIS_ADDR)
		depends_on:
			- mysql
			- redis
	
	mysql:
		image: mysql:8.0
		ports:
			- "3306:3306"
		environment:
			MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
			MYSQL_DATABASE: come 
		volumes:
			- mysql_data:/var/lib/mysql
			- ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

	redis:
		image: redos:7.0-alpine
		ports:
			- "6379:6379"
		volumes:
			- redis_data:/data
		command redis-server --appendonly yes
	
volumes:
	mysql_data:
	redis_data: